### ISSUE TITLE
How do i add sp metadata in a static file rather then generating it on request ?

### ISSUE THREAD

**Issue by samtheprogrammer** [ulisesbocchio/spring-boot-security-saml#12]

**Comment by ulisesbocchio** [comment]
On `ServiceProviderBuilder` you have methods:
* `metadataGenerator(MetadataGenerator):MetadataGeneratorConfigurer`
* `extendedMetadata():ExtendedMetadataConfigurer`

that allows you to configure most aspects of the SP metadata, but the SP metadata is always generated based on the configuration and never from a static file. This is a `spring-security-saml` limitation, the configuration has to be done programatically. Although with this library it's quite straight forward since you have a great variety of DSL methods and static configuration properties that you can use.

**Comment by samtheprogrammer** [comment]
thanks a lot this is very helpful
