### ISSUE TITLE
spring multiple manual sp metadata entry

### ISSUE THREAD

**Issue by samtheprogrammer** [ulisesbocchio/spring-boot-security-saml#18]
Hi for my requirement i need to set multiple sp metadata in a single sp 
the document 

http://docs.spring.io/spring-security-saml/docs/current/reference/html/configuration-metadata.html#configuration-entity-alias

according to the spring docs their is a way to achieve this. How to achieve this if i am using ur library

Thanks in advance 

SAM

**Comment by ulisesbocchio** [comment]
> The entity alias functionality can only be used together with pre-configured metadata (see Section 7.1.2, “Pre-configured metadata”). The entity alias is specified in the extended metadata of each of the configured service providers.

> Spring SAML doesn't enforce any limitations on which Identity Provider can be deliver messages to which of the local Service Providers. In case your application requires similar rules (for example only certain tenants can authenticate using a specific IDP), make sure to implement them for example in your SAMLUserDetailsService (for single sign-on).

> Selection of the correct Service Provider instance based on URL is performed inside SAMLContextProviderImpl class.

`ExtendedMetadata` and `SAMLContextProvider` are beans that can be overridden using this plugin. So basically you just have to add bean definitions for those two types with your customization. For `SAMLContextProvider` you can use `DSLSAMLContextProviderImpl` from the plugin since `SAMLContextProviderImpl` uses `@Autowired` and the dependencies it looks for won't resolve using this plugin but the DSL version will work just fine.
