### ISSUE TITLE
How to use SAML authentication along side other authentication modes.

### ISSUE THREAD

**Issue by zampettim** [ulisesbocchio/spring-boot-security-saml#36]
How would one configure the SAML security so that is can be used alongside other configurations, like basic auth, in a Spring Boot app?

I've tried to use a separate static implementation of Spring Boot's WebSecurityConfigurerAdapter to only apply the configuration to a subset of the url paths, (like is documented for other Spring Boot multi-authentication use cases) and I keep getting the following when trying to start the app.

Caused by: org.springframework.security.config.annotation.AlreadyBuiltException: This object has already been built at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:44) at com.github.ulisesbocchio.spring.boot.security.saml.bean.SAMLConfigurerBean.init(SAMLConfigurerBean.java:225) at com.github.ulisesbocchio.spring.boot.security.saml.bean.SAMLConfigurerBean.init(SAMLConfigurerBean.java:137)

My implementation looks like and I configure everything else via properties:

@Configuration  
@EnableSAMLSSO    
public static class SAMLSecurityConfiguration extends WebSecurityConfigurerAdapter
{
    @Bean
    SAMLConfigurerBean saml()
    {
        return new SAMLConfigurerBean();
    }
    
    @Override
    protected void configure(HttpSecurity http) throws Exception
    {
        //http.antMatcher("/saml/**")
        http.httpBasic().disable()
            .csrf().disable()
            .anonymous()
          .and()
            .apply(saml());
    }
}

**Comment by zampettim** [comment]
Any chance you can review and comment on this?

**Comment by ulisesbocchio** [comment]
@zampettim sorry for the delay, I'll look into this soon. Have you tried applying the saml config first?

**Comment by zampettim** [comment]
I'm not sure what you mean by "applying the saml config first". I've been able to avoid the error related to the "This object has already been built at" if it put the @EnableSAMLSSO at the class level or on the methods that try to enable basic auth or form login, but then SAML login in the only configuration in place. I'm sure I'm doing something wrong, but I cannot get past the "already been built" error when trying to support both form login and SAML login.

**Comment by ulisesbocchio** [comment]
By applying the saml config first I mean using the config that you have, using the `SAMLConfigurerBean` within your own `WebSecurityConfigurerAdapter`, which you have. Now, you can go and try to add your other security config within the same `WebSecurityConfigurerAdapter` to "live" with the saml config. If you create a second `WebSecurityConfigurerAdapter` I would try to define an order to them. With the `@Ordered` annotation. Just be aware that creating a separate `WebSecurityConfigurerAdapter` creates a separate filter chain proxy. Then you end up having at least 2 of those that are executed in the order your define. The filter chain proxies are just one filter that delegate into the security context filters that end up being configured for each `WebSecurityConfigurerAdapter` your define.
I need to dig into how to configure 2 types of authentication mechanisms with this plugin.

**Comment by zampettim** [comment]
So we figured this out, and just getting around to answering this. We had to move the SAML configuration into a separate class with the @Configuration and @EnableWebSecurity method on the class. 
``
@EnableWebSecurity
@Configuration
@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER - 12)
public class SamlSecurityConfiguration {

    @Configuration
    @Order(SecurityProperties.ACCESS_OVERRIDE_ORDER - 12)
    @EnableSAMLSSO
    public static class SAMLSecurityConfiguration extends ServiceProviderConfigurerAdapter {

        @Bean
        SAMLConfigurerBean saml() {
            return new SAMLConfigurerBean();
        }

        @Override
        public void configure(HttpSecurity http) throws Exception {
            http.antMatcher("/saml/**")
                    .httpBasic().disable()
                    .authorizeRequests()
                        .requestMatchers(saml().endpointsMatcher()).permitAll()
                        .anyRequest().authenticated()
                .and()
                    .rememberMe()
                        .rememberMeServices(this.persistentTokenBasedRememberMeServices)
            ;
        }

        @Override
        public void configure(ServiceProviderBuilder serviceProvider) throws Exception {
            String[] cookies;
            if ( logoutCookies != null )
                cookies = logoutCookies.split(",");
            else cookies = null;

            serviceProvider
                    .sso()
                        .defaultSuccessURL(this.defaultSuccessUrl)
                        .successHandler(this.successHandler)
                    .and()
                        .logout()
                            .localHandler(new CookieClearingLogoutHandler(cookies))
                    .and()
                        .authenticationProvider()
                            .userDetailsService(this.platformDaoAuthenticationProvider)
                    .and()
                        .metadataGenerator()
                            .includeDiscoveryExtension(true);
        }
``

Then, on a second class, the rest of the Spring Security configuration is enabled. The key is that this class does NOT have the @EnableWebSecurity, and includes a static class that exends WebSecurityConfigurerAdapter, but has the @Order annotation that forces it to be loaded After the class from the SAML class. 

The basic idea is that the SAML config is built first, and then the rest of the config. SAML is configured to only protect the /saml/ path of URLs. Otherwise, standard Spring Security is used. The idea is that you arrange for the application to redirect the user to use the /saml/login URL when you want to initiate the SAML-based login. That can be done a number of ways. The SAML login process is executed, and when the IdP returns, Spring Security configures the normal authentication process using Cookies or Tokens. Then, requests to other aspects of the application will be treated normally, and everything just works.

**Comment by ulisesbocchio** [comment]
Interesting approach, If you ever have time I would love for you to submit a PR to the samples repo with  a working sample of this mechanism.
At my place of work we have a similar approach, but we actually run an OAuth2 authorization server, on which the /authorize endpoint is protected with SAML login. Basically, is an OAuth2 server, but when you initiate SSO on the oauth2 server, SAML kicks in since the oauth2 sso endpoint is protected with SAML. Then, after SAML redirects back we authorize the user automatically with the SAML information, and redirect back to the user with an OAuth2 code, that can be exchanged for a pair of tokens. All in all, client applications are oblivious of the fact that SAML is going on, they integrate 100% through OAuth2 with the Authorization Server.
On the Authorization Server, the config you explain is similar, 2 security contexts, with SAML protecting part of the application.

**Comment by srinitrack** [comment]
@zampettim  Can you please submit the code as a sample app for future reference.

**Comment by PatrikSteuer** [comment]
I tried to change my implementation to use saml and basic. I get following error while using saml: 
o.s.security.saml.SAMLProcessingFilter   : Authentication request failed: org.springframework.security.authentication.ProviderNotFoundException: No AuthenticationProvider found for org.springframework.security.saml.SAMLAuthenticationToken

Do I have to provide the AuthenticationProvider as part of my WebSecurityConfigurerAdapter or somewhere else? Any help is appreciated

**Comment by ulisesbocchio** [comment]
@PatrikSteuer things start to get weird when you have 2 security mechanisms within a Spring Boot app. Definitely something that should be improved upon from the Spring Security team. Unfortunately in my experience most errors seen when trying to use 2 security contexts are not really representative what truly is going on, so that error by itself doesn't really tell me much except for the obvious, the saml security  configuration is unable to find the security provider.
SecurityProvider gets "created" automatically by the saml configuration when it's the only security being configured, by introducing a second configuration, I'm not sure how Spring Security is getting confused. I would need you to create a repo that I can access with your exact configuration to be able to troubleshoot.
One thing I would try though, is to see which security context is loading first, and expose SecurityProvider from that context as a bean so it could be used by the second security configuration
