### ISSUE TITLE
@EnableSAMLSSO on @Configuation

### ISSUE THREAD

**Issue by chriswhite199** [ulisesbocchio/spring-boot-security-saml#72]
I'm having issues trying to toggle `@EnableSAMLSSO` on a configuration (for example trying to launch the boot application with a profile).

The docs note:

> Add the @EnableSAMLSSO annotation to your Spring Boot Application on any @Configuration class:

So i have the following, trying to only configure when a property is set:

    @Configuration
    @EnableSAMLSSO
    @ConditionalOnProperty(value="security.saml.enable", matchIfMissing=true, havingValue="true")
    public class SAMLSecurityConfig extends WebSecurityConfigurerAdapter {
       // as per the docs: https://github.com/ulisesbocchio/spring-boot-security-saml#using-websecurityconfigureradapter
    }

And this works fine to disable saml when the property is set to false. But when the property is not set, i get the following error:

> Error creating bean with name 'springSecurityFilterChain' ... This object has already been built.

Is there something i'm obviously doing wrong? I don't see an example of `@EnableSAMLSSO` being set on anything other than the Application class in the samples repository.

**Comment by chriswhite199** [comment]
You can easily reproduce this by moving the `@ENableSAMLSSO` annotation in the okta2 sample project from the `OktaSSODemoApplication2` class to the `MyServiceProviderConfig`:

    @Configuration
    @EnableSAMLSSO
    public static class MyServiceProviderConfig extends WebSecurityConfigurerAdapter {

**Comment by bduchesneau** [comment]
Using Spring Boot 2 and spring-boot-security-saml 1.16

I'm also trying to do the same thing but with separate spring profiles.  If I move the @EnableSAMLSSO annotation anywhere besides the @SpringBootApplication class I get the error:

WARN  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is org.springframework.security.config.annotation.AlreadyBuiltException: This object has already been built
INFO  - Unregistering JMX-exposed beans on shutdown
INFO  - Shutting down Quartz Scheduler
INFO  - Scheduler scheduler_$_NON_CLUSTERED shutting down.
INFO  - Scheduler scheduler_$_NON_CLUSTERED paused.
INFO  - Scheduler scheduler_$_NON_CLUSTERED shutdown complete.
INFO  - Shutting down ExecutorService 'threadPoolTaskExecutor'
INFO  - Closed connection [connectionId{localValue:2, serverValue:1132383}] to vpmongo-dev.valpak.com:27017 because the pool has been closed.
INFO  - Stopping service [Tomcat]

**Comment by chriswhite199** [comment]
See https://github.com/ulisesbocchio/spring-boot-security-saml-samples/issues/3#issuecomment-269235667 - this approach worked for me (using a second configuration class and importing it directly from the main application class)

**Comment by bduchesneau** [comment]
Thanks. The first option worked for me in combination with @Profile("sso")

**Comment by ulisesbocchio** [comment]
glad you guys figured it out. This are problems with the way Spring Security loads. My guess is that you guys may have another auth mechanism besides samlsso bootstrapping. Maybe basic auth? Anyway, closing since you guys are good.
